import Link from 'next/link';
import { notFound } from 'next/navigation';
const projects:any={
 'ludo-live':{icon:'🎲',title:'Ludo Live',type:'Multiplayer Gaming Platform',intro:'A production multiplayer game platform with player experiences and a substantial admin/product ecosystem.',repo:'https://github.com/MrDan001/ludo-live',stack:['Next.js','TypeScript','PostgreSQL','Railway'],features:['Multiplayer game experiences','Missions and reward systems','Tournament and admin tooling','Player shop and inventory systems','Player audit and transaction visibility','Production deployment and debugging']},
 'ehealthcare':{icon:'🩺',title:'eHealthcare',type:'Healthcare Platform',intro:'An upcoming healthcare product in the portfolio. The case study will be expanded with verified repository details and screenshots as the project is finalized.',repo:'https://github.com/MrDan001/ehealthcare-system',stack:['Next.js','TypeScript','PostgreSQL'],features:['Healthcare-focused digital experience','Service and information workflows','Product UI and system design','Production-ready architecture']},
 'garrison-market':{icon:'📦',title:'Garrison Market',type:'Inventory & Business Management',intro:'A business operations app for shop owners and staff to manage inventory, staff, sales and day-to-day operations from one place.',repo:'https://github.com/MrDan001/garrison-market',stack:['Next.js','TypeScript','Database'],features:['Inventory management','Staff operations','Sales workflows','Day-to-day business management','Single-place operational view']},
 'the-africa-plug':{icon:'▶',title:'The African Plug',type:'Media & Content Platform',intro:'A content platform focused on media and publishing, including video content and production content updates.',repo:'https://github.com/MrDan001/the-africa-plug',stack:['Next.js','TypeScript','Media'],features:['Video/media section','Publishing workflow','Content updates','Production deployment']}
};
export function generateStaticParams(){return Object.keys(projects).map(slug=>({slug}))}
export default async function Project({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects[slug];if(!p)return notFound();return <><nav className="nav"><div className="wrap" style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Link className="brand" href="/">Mifi<span>.</span></Link><div className="links"><Link href="/#work">WORK</Link><Link href="/#about">ABOUT</Link><Link href="/#contact">CONTACT</Link></div></div></nav><main className="case wrap"><Link href="/#work" style={{color:'#20d9ff',fontSize:13}}>← Back to projects</Link><div className="case-hero" style={{marginTop:28}}><div><div className="eyebrow">CASE STUDY · {p.type.toUpperCase()}</div><h1>{p.icon} {p.title}</h1><p className="case-intro">{p.intro}</p><div className="actions"><a className="btn primary" href={p.repo} target="_blank">View GitHub ↗</a><a className="btn" href="/#contact">Discuss a project</a></div></div><div className="case-visual">{p.icon}</div></div><section className="case-section"><h2>Technology</h2><div className="tags">{p.stack.map((x:string)=><span className="tag" key={x}>{x}</span>)}</div></section><section className="case-section"><h2>What I built</h2><div className="facts">{p.features.map((x:string,i:number)=><div className="fact" key={x}><small>{String(i+1).padStart(2,'0')}</small><strong>{x}</strong></div>)}</div></section><section className="case-section"><h2>Why it belongs here</h2><p className="case-intro">This case study is intentionally focused on the product, the systems behind it, and the engineering decisions that make it useful. Screenshots, architecture notes, and deeper implementation details can be added as the project is documented.</p></section></main><footer><div className="wrap">© 2026 Mifitech · <Link href="/">Back home</Link></div></footer></>}